In [2]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5], [7, -2, -6, 1, -2], [4, 5, -3, 3, 9], [4, 6, 7, 2, -1], [8, -8, 8, -8, 9]])
print(a)

[[ 1  2  3  4  5]
 [ 7 -2 -6  1 -2]
 [ 4  5 -3  3  9]
 [ 4  6  7  2 -1]
 [ 8 -8  8 -8  9]]


In [ ]:
# Obtem a primeira linha (0), o primeiro valor (1),(começa o fatiamento) na coluna índice quatro (4) e na última coluna (5 ou 4)
print(a[0:1, 4:5])

In [ ]:
print(a[1:2, 3:4])

In [ ]:
print(a[0:1, 0:1])

In [ ]:
print(a[1:2, 1:2])

- Apresente os valores da Diagonal Principal

- Apresente os valores da Diagonal Secundária

- Apresente o somatório da Diagonal principal

- Apresente o somatório da Diagonal secundária

In [3]:
aux_tres = 0; aux_quatro = 1;
aux_um = 4; aux_dois = 5;

soma_um = 0; soma_dois = 0

print('Diagonal secundária')
for k, v in enumerate(a):
    print(a[aux_tres:aux_quatro, aux_um:aux_dois])
    soma_dois += int(a[aux_um:aux_dois, aux_tres:aux_quatro])
    aux_um -= 1; aux_dois -= 1; aux_tres += 1; aux_quatro += 1
    
aux_tres = 0; aux_quatro = 1;
aux_um = 0; aux_dois = 1;

print('\nDiagonal principal')
for k, v in enumerate(a):
    print(a[aux_um:aux_dois, aux_tres:aux_quatro])
    soma_um += int(a[aux_um:aux_dois, aux_tres:aux_quatro])
    aux_um += 1; aux_dois += 1; aux_tres += 1; aux_quatro += 1

print(soma_um)
print(soma_dois)

Diagonal secundária
[[5]]
[[1]]
[[-3]]
[[6]]
[[8]]

Diagonal principal
[[1]]
[[-2]]
[[-3]]
[[2]]
[[9]]
7
17
