# 20° Exercício 

## 1) Subtração

In [2]:
import numpy as np

In [4]:
A = np.array([[4, 11, 1, 3], [-6, 13, 0, 4], [8, -10, -2, -5]])
B = np.array([[7, -5, 18, 34], [-8, 6, -16, 21], [4, 7, 19, 28]])

print(A - B)

[[ -3  16 -17 -31]
 [  2   7  16 -17]
 [  4 -17 -21 -33]]


In [5]:
A = np.array([[5, -10], [6, -9], [7, 8]])
B= np.array([[7, 10], [-8, 12], [9, 14]])

print(A - B)

[[ -2 -20]
 [ 14 -21]
 [ -2  -6]]


In [6]:
A = np.array([[5, -7, 15, -9], [8, 10, 8, 11]])
B = np.array([[6, -1, 13, 31], [9, 9, 20, -1]])

print(A - B)

[[ -1  -6   2 -40]
 [ -1   1 -12  12]]


In [7]:
A = np.array([[3, 7, 23], [-2, 8, 24]])
B = np.array([[36, 9, 13], [-8, -10, 30]])

print(A - B)

[[-33  -2  10]
 [  6  18  -6]]


In [8]:
A = np.array([[9, 13, 23], [-8, 45, -46], [10, 89, 36]])
B = np.array([[14, -8, 34], [-15, 9, 35], [6, 10, 39]])

print(A - B)

[[ -5  21 -11]
 [  7  36 -81]
 [  4  79  -3]]


In [11]:
A = np.array([[18, 36, 50], [-20, -19, 60],[31, 40, -37]])
B = np.array([[36, -17, 25], [90, 18, -50], [-40, 20, -38]])

print(A - B)

[[ -18   53   25]
 [-110  -37  110]
 [  71   20    1]]


In [12]:
A = np.array([[1, 8, -7, -13], [6, -5, 8, -24], [9, 9, -10, -60]])
B = np.array([[9, 7, 3, -10], [13, -5, 4, 8], [4, -8, 7, 3]])

print(A - B)

[[ -8   1 -10  -3]
 [ -7   0   4 -32]
 [  5  17 -17 -63]]


In [13]:
A = np.array([[-15, 8, 9], [3, -2, 1], [7, -1, 4]])
B = np.array([[17, -8, 9], [13, 2, 1], [6, -8, 5]])

print(A - B)

[[-32  16   0]
 [-10  -4   0]
 [  1   7  -1]]


In [14]:
A = np.array([[-8, 13, 16], [9, 14, 21]])
B = np.array([[-22, 15, -1], [9, -6, -8]])

print(A - B)

[[14 -2 17]
 [ 0 20 29]]


In [15]:
A = np.array([[19, 36], [22, -84]])
B = np.array([[36, -8], [9, 4]])

print(A - B)

[[-17  44]
 [ 13 -88]]


## 2) Multiplicação

In [17]:
A = np.array([[5, 3, 10], [6, 9, 15]])
B = np.array([[4, 2], [5, 9], [6, 7]])

print(np.dot(A, B))

[[ 95 107]
 [159 198]]


In [18]:
A = np.array([[8, 6, 4, 5, 10],[10, 7, 8, -9, 7]])
B = np.array([[8, 10], [5, -1], [3, 3], [4, 4], [2, -2]])

print(np.dot(A, B))

[[146  86]
 [117  67]]


In [19]:
A = np.array([[8, -7], [-1, 4]])
B = np.array([[4, 7], [-5, 8]])

print(np.dot(A , B))



[[ 67   0]
 [-24  25]]


In [20]:
A = np.array([[4, 5, 8, 10], [9, 11, 12, 5]])
B = np.array([[5, 6], [4, 7], [20, 8], [10, 5]])

print(np.dot(A, B))

[[300 173]
 [379 252]]


In [21]:
A = np.array([[5, 4, 3, 2, 9, 10], [4, -13, 7, 12, 14, 2]])
B = np.array([[8], [9], [4], [5], [6], [7]])

print(np.dot(A, B))

[[222]
 [101]]
