# 14° Exercício
Crie 4 matrizes: 2x4, 4x5, 5x3 e 3x4. Faça a multiplicação dessas matrizes até serem uma só matriz.

In [9]:
import numpy as np

A = np.array([[4, 6, 7, 8], [5, 9, 10, 0]])
B = np.array([[7, 8, 9, 10, 7], [2, 5, 1, 7, 8], [67, 9, 0, 10, 3], [10, 23, 4, 8, 5]])
A_vezes_B = np.dot(A, B)
print(A_vezes_B)

C = np.array([[4, 2, 20], [45, 23, 10], [3, 7, 9], [56, 43, 12], [5, 3, 12]])
D = np.array([[5, 7, 9, 0], [23, 13, 5, 8], [23, 10 ,2 ,4]])
C_vezes_D = np.dot(C, D)
print('\n', C_vezes_D)

print('\nResultado final: \n', np.dot(A_vezes_B, C_vezes_D))

[[589 309  74 216 137]
 [723 175  54 213 137]]

 [[ 526  254   86   96]
 [ 984  714  540  224]
 [ 383  202   80   92]
 [1545 1071  743  392]
 [ 370  194   84   72]]

Resultado final: 
 [[1026622  643094  395430  227104]
 [ 952955  574201  330765  206936]]
