# 8° Exercício
Crie três matrizes: 3x4, 5x6, 2x3 e multiplique a primeira por 2, a segunda por 5 e a terceira 4.

In [9]:
import numpy as np

matriz1 = np.arange(12).reshape(3, 4)
matriz2 = np.arange(30).reshape(5, 6)
matriz3 = np.arange(6).reshape(2, 3)

print('Matriz um: \n{}'.format(matriz1 * 2))
print('Matriz dois: \n{}'.format(matriz2 * 5))
print('Matriz três: \n{}'.format(matriz3 * 4))

Matriz um: 
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
Matriz dois: 
[[  0   5  10  15  20  25]
 [ 30  35  40  45  50  55]
 [ 60  65  70  75  80  85]
 [ 90  95 100 105 110 115]
 [120 125 130 135 140 145]]
Matriz três: 
[[ 0  4  8]
 [12 16 20]]
