# 3° Exercício
### Crie duas matrizes a partir de dois arrays

In [4]:
# Solução:
import numpy as np

array_um = np.arange(10)
array_dois = np.arange(16)

# Convertendo

array_um = array_um.reshape(2, 5)
array_dois = array_dois.reshape(4, 4)

print('Matriz um: \n\n{}'.format(array_um))
print('\nMatriz dois: \n\n{}'.format(array_dois))

Matriz um: 

[[0 1 2 3 4]
 [5 6 7 8 9]]

Matriz dois: 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
